[tool.poetry]
name = "object-stores"
version = "0.1.0"
description = "Python bindings and integrations for the rust object_store crate."
authors = ["Robert Pack <robstar.pack@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"

# pip dependencies
bandit = "^1.7.4"
black = "^22.8.0"
flake8 = "^5.0.4"
flake8-bugbear = "^22.8.23"
maturin = "^0.13.2"
mkdocs = "^1.3.1"
mkdocs-material = "^8.4.3"
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-datadir = "^1.3.1"
ipykernel = "^6.15.2"
pytest-cov = "^3.0.0"
mlflow-skinny = "^1.28.0"
duckdb = "^0.5.0"
mkdocstrings = {version = "^0.19.0", extras = ["python"]}

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
known_first_party = ["object_store"]

[tool.bandit]
exclude_dirs = ["object-store/tests"]
