[build-system]
requires = ["maturin>=0.11,<0.15"]
build-backend = "maturin"

[project]
name = "object-store"
requires-python = ">=3.8"
readme = "README.md"
keywords = ["object-store", "azure", "aws", "gcp"]
authors = [{ name = "Robert Pack", email = "robstar.pack@gmail.com" }]
classifier = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "License :: OSI Approved",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python",
  "Programming Language :: Rust",
]

[project.optional-dependencies]
pyarrow = ["pyarrow>=7.0"]

[project.urls]
repository = "https://github.com/roeap/object-store-python"

[tool.maturin]
sdist-include = ["Cargo.lock"]

[tool.coverage.report]
fail_under = 85
exclude_lines = [
  "pragma: no cover",
  "@overload",
  "except ImportError",
  "if TYPE_CHECKING:",
  "from typing_extensions import ",
]
