name: Release to PyPI

on:
  push:
    tags: ["v*"]

env:
  MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
  validate-release-tag:
    name: Validate git tag
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: compare git tag with cargo metadata
        working-directory: object-store/
        run: |
          PUSHED_TAG=${GITHUB_REF##*/}
          CURR_VER=$( grep version Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          if [[ "${PUSHED_TAG}" != "python-v${CURR_VER}" ]]; then
            echo "Cargo metadata has version set to ${CURR_VER}, but got pushed tag ${PUSHED_TAG}."
            exit 1
          fi

  release-pypi-mac:
    needs: validate-release-tag
    name: PyPI release on Mac
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v3

      - uses: messense/maturin-action@v1
        name: Publish to pypi (without sdist)
        with:
          target: ${{ matrix.target }}
          command: publish
          args: -m object-store/Cargo.toml --no-sdist

  release-pypi-mac-universal2:
    needs: validate-release-tag
    name: PyPI release on Mac universal 2
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: messense/maturin-action@v1
        name: Publish to pypi (without sdist)
        with:
          target: ${{ matrix.target }}
          command: publish
          args: -m object-store/Cargo.toml --no-sdist --universal2

  release-pypi-windows:
    needs: validate-release-tag
    name: PyPI release on Windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - uses: messense/maturin-action@v1
        name: Publish to pypi (without sdist)
        with:
          target: x86_64-pc-windows-msvc
          command: publish
          args: -m object-store/Cargo.toml --no-sdist

  release-pypi-manylinux:
    needs: validate-release-tag
    name: PyPI release manylinux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: messense/maturin-action@v1
        name: Publish manylinux to pypi x86_64 (with sdist)
        with:
          target: x86_64-unknown-linux-gnu
          command: publish
          args: -m object-store/Cargo.toml

      - uses: messense/maturin-action@v1
        name: Publish manylinux to pypi aarch64 (without sdist)
        with:
          target: aarch64-unknown-linux-gnu
          command: publish
          args: -m object-store/Cargo.toml --no-sdist
